# Generated by Django 4.0.6 on 2022-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('create_by', models.CharField(blank=True, max_length=150, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=150, null=True)),
                ('update_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
